// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package txwhiteboard is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	AddLine
	AddLineContent
	Point
*/
package txwhiteboard

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddLine struct {
	Type             *string         `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Seq              *uint32         `protobuf:"varint,2,req,name=seq" json:"seq,omitempty"`
	Content          *AddLineContent `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *AddLine) Reset()                    { *m = AddLine{} }
func (m *AddLine) String() string            { return proto.CompactTextString(m) }
func (*AddLine) ProtoMessage()               {}
func (*AddLine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddLine) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *AddLine) GetSeq() uint32 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *AddLine) GetContent() *AddLineContent {
	if m != nil {
		return m.Content
	}
	return nil
}

type AddLineContent struct {
	BoardId          *string  `protobuf:"bytes,1,req,name=boardId" json:"boardId,omitempty"`
	Uid              *string  `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	Time             *uint32  `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	ColorRGBA        *uint32  `protobuf:"varint,4,req,name=colorRGBA" json:"colorRGBA,omitempty"`
	Width            *int32   `protobuf:"varint,5,req,name=width" json:"width,omitempty"`
	Scale            *int32   `protobuf:"varint,6,req,name=scale" json:"scale,omitempty"`
	UpdateTime       *uint32  `protobuf:"varint,7,req,name=updateTime" json:"updateTime,omitempty"`
	Hidden           *bool    `protobuf:"varint,8,req,name=hidden" json:"hidden,omitempty"`
	Points           []*Point `protobuf:"bytes,9,rep,name=points" json:"points,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AddLineContent) Reset()                    { *m = AddLineContent{} }
func (m *AddLineContent) String() string            { return proto.CompactTextString(m) }
func (*AddLineContent) ProtoMessage()               {}
func (*AddLineContent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddLineContent) GetBoardId() string {
	if m != nil && m.BoardId != nil {
		return *m.BoardId
	}
	return ""
}

func (m *AddLineContent) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *AddLineContent) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *AddLineContent) GetColorRGBA() uint32 {
	if m != nil && m.ColorRGBA != nil {
		return *m.ColorRGBA
	}
	return 0
}

func (m *AddLineContent) GetWidth() int32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *AddLineContent) GetScale() int32 {
	if m != nil && m.Scale != nil {
		return *m.Scale
	}
	return 0
}

func (m *AddLineContent) GetUpdateTime() uint32 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

func (m *AddLineContent) GetHidden() bool {
	if m != nil && m.Hidden != nil {
		return *m.Hidden
	}
	return false
}

func (m *AddLineContent) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

type Point struct {
	X                *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	Seq              *int32 `protobuf:"varint,3,req,name=seq" json:"seq,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Point) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Point) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Point) GetSeq() int32 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func init() {
	proto.RegisterType((*AddLine)(nil), "txwhiteboard.AddLine")
	proto.RegisterType((*AddLineContent)(nil), "txwhiteboard.AddLineContent")
	proto.RegisterType((*Point)(nil), "txwhiteboard.Point")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0x3b, 0x31,
	0x10, 0xc5, 0xd9, 0x6c, 0xd3, 0xed, 0x4e, 0xdb, 0x3f, 0x7f, 0x46, 0x91, 0x1c, 0x8a, 0x84, 0x9e,
	0x02, 0x42, 0x0f, 0x05, 0xbd, 0x57, 0x0f, 0x22, 0x78, 0x90, 0xe0, 0x17, 0xa8, 0x4d, 0xb0, 0x81,
	0xba, 0x59, 0x77, 0x53, 0xba, 0xfb, 0xe9, 0x95, 0xcc, 0xee, 0x62, 0x7b, 0x7b, 0xbf, 0x37, 0x93,
	0x79, 0x99, 0x01, 0x08, 0xb6, 0x0e, 0xab, 0xb2, 0xf2, 0xc1, 0xe3, 0x2c, 0x34, 0xa7, 0xbd, 0x0b,
	0xf6, 0xc3, 0x6f, 0x2b, 0xb3, 0xfc, 0x84, 0x6c, 0x63, 0xcc, 0xab, 0x2b, 0x2c, 0x22, 0x8c, 0x42,
	0x5b, 0x5a, 0x91, 0x48, 0xa6, 0x72, 0x4d, 0x1a, 0xff, 0x43, 0x5a, 0xdb, 0x6f, 0xc1, 0x24, 0x53,
	0x73, 0x1d, 0x25, 0x3e, 0x40, 0xb6, 0xf3, 0x45, 0xb0, 0x45, 0x10, 0xa9, 0x64, 0x6a, 0xba, 0x5e,
	0xac, 0xce, 0x07, 0xae, 0xfa, 0x69, 0x4f, 0x5d, 0x8f, 0x1e, 0x9a, 0x97, 0x3f, 0x09, 0xfc, 0xbb,
	0xac, 0xa1, 0x80, 0x8c, 0xde, 0xbc, 0x98, 0x3e, 0x73, 0xc0, 0x18, 0x7b, 0x74, 0x86, 0x62, 0x73,
	0x1d, 0x25, 0x7d, 0xce, 0x7d, 0x59, 0xca, 0x9c, 0x6b, 0xd2, 0xb8, 0x80, 0x7c, 0xe7, 0x0f, 0xbe,
	0xd2, 0xcf, 0x8f, 0x1b, 0x31, 0xa2, 0xc2, 0x9f, 0x81, 0xd7, 0xc0, 0x4f, 0xce, 0x84, 0xbd, 0xe0,
	0x92, 0x29, 0xae, 0x3b, 0x88, 0x6e, 0xbd, 0xdb, 0x1e, 0xac, 0x18, 0x77, 0x2e, 0x01, 0xde, 0x02,
	0x1c, 0x4b, 0xb3, 0x0d, 0xf6, 0x3d, 0x66, 0x64, 0x34, 0xea, 0xcc, 0xc1, 0x1b, 0x18, 0xef, 0x9d,
	0x31, 0xb6, 0x10, 0x13, 0xc9, 0xd4, 0x44, 0xf7, 0x84, 0x77, 0x30, 0x2e, 0xbd, 0x2b, 0x42, 0x2d,
	0x72, 0x99, 0xaa, 0xe9, 0xfa, 0xea, 0xf2, 0x16, 0x6f, 0xb1, 0xa6, 0xfb, 0x96, 0xe5, 0x3d, 0x70,
	0x32, 0x70, 0x06, 0x49, 0x43, 0x1b, 0x73, 0x9d, 0x34, 0x91, 0x5a, 0xda, 0x94, 0xeb, 0xa4, 0x1d,
	0x0e, 0x9e, 0x12, 0x47, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x08, 0xd7, 0x60, 0x43, 0xbc, 0x01,
	0x00, 0x00,
}
